name = "ScikitRF"
uuid = "a7cb2933-f38b-450b-a518-90520ecaf05f"
version = "0.1.0"
authors = ["Kaj Wiik <kaj.wiik@utu.fi>"]

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
CondaPkg = "0.2.33"
PythonCall = "0.9.29"
Reexport = "1.2.2"
